# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75aecd0374b544053912bb8e131e66c4f17dc5ff78a3ef400f4f552f75a37c18e98228a0cc8193018a99751de23f0773f23182aafb53f8d747161b3db2b68453

test:
  secret_key_base: b0937e9d2a66221b9d71bcedb6efb0e3d5e117588b02510a15ee8c1fd47f4094ffff2f95db8914c76554abbf4a24425ece1ca002e094857c63a1d52f0b823449

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
